version: '3.3'

services:
  nuxt:
    container_name: nuxt_starter
    image: nuxt_starter
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
